### ISSUE TITLE
irmin-graphql: Schema fetching broken with Graphiql

### ISSUE THREAD

**Issue by patricoferris** [mirage/irmin#2040]
Currently if you start the `examples/custom_graphql.exe` example the GraphiQL interface returns an error and the schema exploration is not possible:

```
Error: Introspection must provide input type for arguments.
    at invariant (http://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:25811:11)
    at getInputType (http://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33531:67)
    at buildInputValue (http://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33675:16)
    at http://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:25955:31
    at Array.reduce (<anonymous>)
    at keyValMap (http://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:25954:15)
    at buildInputValueDefMap (http://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33669:36)
    at http://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:33663:15
    at http://cdn.jsdelivr.net/npm/graphiql@0.12.0/graphiql.js:25955:31
    at Array.reduce (<anonymous>)
```

It seems the interface still works, but having the schema documentation to hand is very useful for testing and learning. It seems reverting the following two changes makes it work again (i.e. it needs to be `ContentsKeyValue` and `NodeKeyValue`).

https://github.com/mirage/irmin/pull/1750/files#diff-75527fd1166eaf7260ee082ee27f3241098048ce7ce592c1a605efb98026da70R445

**Comment by zshipko** [comment]
Thanks! Where did that error message come from?

I'm getting a different error message in the graphiql interface even if I change `ContentsKey` and `NodeKey` to `ContentsKeyValue` and `NodeKeyValue` - I will investigate a little more.

**Comment by zshipko** [comment]
Nevermind, your suggested fix works - I just made a PR and will merge it today :smile:
